name = "CFITSIO"
uuid = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "1.0.0"

[deps]
CFITSIO_jll = "b3e40c51-02ae-5482-8a39-3ace5868dcf4"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]